-- MySQL Script generated by MySQL Workbench
-- 09/08/16 21:02:05
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema santauti
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `santauti` ;

-- -----------------------------------------------------
-- Schema santauti
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `santauti` DEFAULT CHARACTER SET utf8 ;
USE `santauti` ;

-- -----------------------------------------------------
-- Table `santauti`.`Pessoa`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `santauti`.`Pessoa` ;

CREATE TABLE IF NOT EXISTS `santauti`.`Pessoa` (
  `CPF` VARCHAR(11) NOT NULL,
  `Nome` VARCHAR(45) NOT NULL,
  `Sobrenome` VARCHAR(45) NOT NULL,
  `Identidade` VARCHAR(45) NOT NULL,
  `DataNascimento` DATE NOT NULL,
  `Rua` VARCHAR(45) NULL,
  `Numero` INT NULL,
  `Bairro` VARCHAR(45) NULL,
  `Apartamento` VARCHAR(45) NULL,
  `Email` VARCHAR(45) NULL,
  `Cep` VARCHAR(45) NULL,
  `Cidade` VARCHAR(45) NULL,
  PRIMARY KEY (`CPF`),
  UNIQUE INDEX `CPF_UNIQUE` (`CPF` ASC),
  UNIQUE INDEX `Identidade_UNIQUE` (`Identidade` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `santauti`.`Profissional`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `santauti`.`Profissional` ;

CREATE TABLE IF NOT EXISTS `santauti`.`Profissional` (
  `Registro` INT NOT NULL,
  `CPF` VARCHAR(11) NOT NULL,
  `Usuario` VARCHAR(45) NOT NULL,
  `Senha` VARCHAR(256) NOT NULL,
  `TipoProfissional` INT NOT NULL,
  PRIMARY KEY (`Registro`, `CPF`),
  UNIQUE INDEX `Usuario_UNIQUE` (`Usuario` ASC),
  INDEX `cpfPessoa_idx` (`CPF` ASC),
  UNIQUE INDEX `CPF_UNIQUE` (`CPF` ASC),
  UNIQUE INDEX `Registro_UNIQUE` (`Registro` ASC),
  CONSTRAINT `fk_cpfProfissional`
    FOREIGN KEY (`CPF`)
    REFERENCES `santauti`.`Pessoa` (`CPF`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `santauti`.`Paciente`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `santauti`.`Paciente` ;

CREATE TABLE IF NOT EXISTS `santauti`.`Paciente` (
  `CPF` VARCHAR(11) NOT NULL,
  `Leito` INT NOT NULL,
  `Box` INT NOT NULL,
  `Profissao` VARCHAR(45) NOT NULL,
  `Convenio` VARCHAR(45) NULL,
  UNIQUE INDEX `CPF_UNIQUE` (`CPF` ASC),
  PRIMARY KEY (`CPF`),
  CONSTRAINT `fk_cpfPaciente`
    FOREIGN KEY (`CPF`)
    REFERENCES `santauti`.`Pessoa` (`CPF`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `santauti`.`Telefone`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `santauti`.`Telefone` ;

CREATE TABLE IF NOT EXISTS `santauti`.`Telefone` (
  `CPF` VARCHAR(11) NOT NULL,
  `Telefone` VARCHAR(45) NOT NULL,
  `TipoTelefone` INT NULL,
  INDEX `cpfPessoa_idx` (`CPF` ASC),
  PRIMARY KEY (`Telefone`, `CPF`),
  CONSTRAINT `fk_cpfTelefone`
    FOREIGN KEY (`CPF`)
    REFERENCES `santauti`.`Pessoa` (`CPF`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `santauti`.`Fichas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `santauti`.`Fichas` ;

CREATE TABLE IF NOT EXISTS `santauti`.`Fichas` (
  `NroAtendimento` INT NOT NULL AUTO_INCREMENT,
  `TipoFicha` INT NOT NULL,
  PRIMARY KEY (`NroAtendimento`),
  UNIQUE INDEX `NroAtendimento_UNIQUE` (`NroAtendimento` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `santauti`.`Responsavel`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `santauti`.`Responsavel` ;

CREATE TABLE IF NOT EXISTS `santauti`.`Responsavel` (
  `Registro` INT NOT NULL,
  `CpfPaciente` VARCHAR(11) NOT NULL,
  PRIMARY KEY (`Registro`, `CpfPaciente`),
  CONSTRAINT `fk_registroProfissional`
    FOREIGN KEY (`Registro`)
    REFERENCES `santauti`.`Profissional` (`Registro`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_cpfPacienteInterno`
    FOREIGN KEY (`CpfPaciente`)
    REFERENCES `santauti`.`Paciente` (`CPF`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `santauti`.`Avaliacao`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `santauti`.`Avaliacao` ;

CREATE TABLE IF NOT EXISTS `santauti`.`Avaliacao` (
  `Registro` INT NOT NULL,
  `CPFPaciente` VARCHAR(11) NOT NULL,
  `NroAtendimento` INT NOT NULL,
  `Data` DATE NOT NULL,
  `HoraCriada` TIME(3) NOT NULL,
  `DataModificada` DATETIME(5) NOT NULL,
  UNIQUE INDEX `NroAtendimento_UNIQUE` (`NroAtendimento` ASC),
  PRIMARY KEY (`Registro`, `CPFPaciente`, `NroAtendimento`),
  CONSTRAINT `fk_registroProfissionalAvaliacao`
    FOREIGN KEY (`Registro`)
    REFERENCES `santauti`.`Profissional` (`Registro`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_cpfPacienteAvaliacao`
    FOREIGN KEY (`CPFPaciente`)
    REFERENCES `santauti`.`Paciente` (`CPF`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_nroAtendimento`
    FOREIGN KEY (`NroAtendimento`)
    REFERENCES `santauti`.`Fichas` (`NroAtendimento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
